/**
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.debugSeq;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqModel#getDebugvars <em>Debugvars</em>}</li>
 *   <li>{@link com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqModel#getSequences <em>Sequences</em>}</li>
 * </ul>
 *
 * @see com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage#getDebugSeqModel()
 * @model
 * @generated
 */
public interface DebugSeqModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Debugvars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Debugvars</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Debugvars</em>' containment reference.
   * @see #setDebugvars(DebugVars)
   * @see com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage#getDebugSeqModel_Debugvars()
   * @model containment="true"
   * @generated
   */
  DebugVars getDebugvars();

  /**
   * Sets the value of the '{@link com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqModel#getDebugvars <em>Debugvars</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Debugvars</em>' containment reference.
   * @see #getDebugvars()
   * @generated
   */
  void setDebugvars(DebugVars value);

  /**
   * Returns the value of the '<em><b>Sequences</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sequences</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequences</em>' containment reference.
   * @see #setSequences(Sequences)
   * @see com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage#getDebugSeqModel_Sequences()
   * @model containment="true"
   * @generated
   */
  Sequences getSequences();

  /**
   * Sets the value of the '{@link com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqModel#getSequences <em>Sequences</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sequences</em>' containment reference.
   * @see #getSequences()
   * @generated
   */
  void setSequences(Sequences value);

} // DebugSeqModel
