/**
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.debugSeq;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Statement, Parameter
{
} // Expression
