/**
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.debugSeq;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
