/*
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DebugSeqAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/arm/cmsis/pack/debugseq/parser/antlr/internal/InternalDebugSeq.tokens");
	}
}
