/*
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.parser.antlr;

import com.arm.cmsis.pack.debugseq.parser.antlr.internal.InternalDebugSeqParser;
import com.arm.cmsis.pack.debugseq.services.DebugSeqGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DebugSeqParser extends AbstractAntlrParser {

	@Inject
	private DebugSeqGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDebugSeqParser createParser(XtextTokenStream stream) {
		return new InternalDebugSeqParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DebugSeqModel";
	}

	public DebugSeqGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DebugSeqGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
