/**
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.debugSeq.impl;

import com.arm.cmsis.pack.debugseq.debugSeq.DapJtagSequence;
import com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage;
import com.arm.cmsis.pack.debugseq.debugSeq.Expression;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Dap Jtag Sequence</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.arm.cmsis.pack.debugseq.debugSeq.impl.DapJtagSequenceImpl#getCnt <em>Cnt</em>}</li>
 *   <li>{@link com.arm.cmsis.pack.debugseq.debugSeq.impl.DapJtagSequenceImpl#getTms <em>Tms</em>}</li>
 *   <li>{@link com.arm.cmsis.pack.debugseq.debugSeq.impl.DapJtagSequenceImpl#getTdi <em>Tdi</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DapJtagSequenceImpl extends ExpressionImpl implements DapJtagSequence
{
  /**
   * The cached value of the '{@link #getCnt() <em>Cnt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCnt()
   * @generated
   * @ordered
   */
  protected Expression cnt;

  /**
   * The cached value of the '{@link #getTms() <em>Tms</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTms()
   * @generated
   * @ordered
   */
  protected Expression tms;

  /**
   * The cached value of the '{@link #getTdi() <em>Tdi</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTdi()
   * @generated
   * @ordered
   */
  protected Expression tdi;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DapJtagSequenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DebugSeqPackage.Literals.DAP_JTAG_SEQUENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getCnt()
  {
    return cnt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCnt(Expression newCnt, NotificationChain msgs)
  {
    Expression oldCnt = cnt;
    cnt = newCnt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT, oldCnt, newCnt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCnt(Expression newCnt)
  {
    if (newCnt != cnt)
    {
      NotificationChain msgs = null;
      if (cnt != null)
        msgs = ((InternalEObject)cnt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT, null, msgs);
      if (newCnt != null)
        msgs = ((InternalEObject)newCnt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT, null, msgs);
      msgs = basicSetCnt(newCnt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT, newCnt, newCnt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getTms()
  {
    return tms;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTms(Expression newTms, NotificationChain msgs)
  {
    Expression oldTms = tms;
    tms = newTms;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS, oldTms, newTms);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTms(Expression newTms)
  {
    if (newTms != tms)
    {
      NotificationChain msgs = null;
      if (tms != null)
        msgs = ((InternalEObject)tms).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS, null, msgs);
      if (newTms != null)
        msgs = ((InternalEObject)newTms).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS, null, msgs);
      msgs = basicSetTms(newTms, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS, newTms, newTms));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getTdi()
  {
    return tdi;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTdi(Expression newTdi, NotificationChain msgs)
  {
    Expression oldTdi = tdi;
    tdi = newTdi;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI, oldTdi, newTdi);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTdi(Expression newTdi)
  {
    if (newTdi != tdi)
    {
      NotificationChain msgs = null;
      if (tdi != null)
        msgs = ((InternalEObject)tdi).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI, null, msgs);
      if (newTdi != null)
        msgs = ((InternalEObject)newTdi).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI, null, msgs);
      msgs = basicSetTdi(newTdi, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI, newTdi, newTdi));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT:
        return basicSetCnt(null, msgs);
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS:
        return basicSetTms(null, msgs);
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI:
        return basicSetTdi(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT:
        return getCnt();
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS:
        return getTms();
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI:
        return getTdi();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT:
        setCnt((Expression)newValue);
        return;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS:
        setTms((Expression)newValue);
        return;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI:
        setTdi((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT:
        setCnt((Expression)null);
        return;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS:
        setTms((Expression)null);
        return;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI:
        setTdi((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__CNT:
        return cnt != null;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TMS:
        return tms != null;
      case DebugSeqPackage.DAP_JTAG_SEQUENCE__TDI:
        return tdi != null;
    }
    return super.eIsSet(featureID);
  }

} //DapJtagSequenceImpl
