/*
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDebugSeqValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(com.arm.cmsis.pack.debugseq.debugSeq.DebugSeqPackage.eINSTANCE);
		return result;
	}
	
}
