package com.arm.cmsis.pack.installer.ui;

public enum ButtonId {
    BUTTON_UNDEFINED, BUTTON_UPTODATE, BUTTON_OFFLINE, BUTTON_DEPRECATED, BUTTON_INSTALL, BUTTON_INSTALL_PLUS,
    BUTTON_RESOLVE, BUTTON_UPDATE, BUTTON_UPDATE_PLUS, BUTTON_UNPACK, BUTTON_UNPACK_PLUS, BUTTON_REMOVE, BUTTON_DELETE,
    BUTTON_DELETE_ALL, BUTTON_COPY, BUTTON_REPOSITORY, BUTTON_COPY_REPOSITORY, BUTTON_COPY_TAG, BUTTON_1PACK,
    BUTTON_PACKS, BUTTON_IMPORT,

}
