/*
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DebugSeqStandaloneSetup extends DebugSeqStandaloneSetupGenerated {

	def static void doSetup() {
		new DebugSeqStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
