/*
 * generated by Xtext 2.10.0
 */
package com.arm.cmsis.pack.debugseq.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDebugSeqScopeProvider extends DelegatingScopeProvider {
}
